site_name: "Architect's Insight Hub: Elevate Your Learning Experience"
nav:
  - Home: index.md
  - Summaries:
    - a16z:
      - AI: summaries/a16z/a16z_ai.md
      - Company building: summaries/a16z/a16z_company_building.md
      - Podcast: summaries/a16z/a16z_podcast.md
    - davos:
      - year 2024: summaries/davos/davos_2024.md
    - devoxx:
      - cern 2023: summaries/devoxx/devoxx_cern_2023.md
    - computer scientists:
      - Allan Kay: summaries/computer_scientists/allan_kay_mistral.md
      - Donald Knuth: summaries/computer_scientists/donald_knuth_mistral.md
    - gdc:
      - gdc 2023: summaries/gdc/gdc_2023.md
    - google:      
      - deep mind learning: summaries/google/deep_mind_learning.md
      - io 2023: summaries/google/google_io_2023.md
      - tech talks: summaries/google/google_talks_tech.md
    - goto: 
      - design thinking/ui/ux: summaries/goto/goto_dt_ui_ux.md
      - event driven arch 2023: summaries/goto/goto_eda_2023.md
      - frontend: summaries/goto/goto_FE_v4.md
      - programming languages: summaries/goto/goto_programming_lang.md
      - software architecture: summaries/goto/goto_sw_arch_list.md
    - jakartaee:
      - jakartaone 2023: summaries/jakartaee/jakartaone_2023.md
    - java:
      - jvm language summit: summaries/java/jvm_language_summit_2023_mistral_fp16.md
      - level up java dev day: summaries/java/level_up_java_dev_day_mistral.md
      - road to 21: summaries/java/road_to_21_mistral.md
    - Javascript/Typescript:
      - ng conf 2022: summaries/web_dev/ng_conf_2022.md
      - ng conf 2023: summaries/web_dev/ng_conf_2023_neuralchat.md
      - nordic.js 2022: summaries/web_dev/nordic_js_2022.md
      - reliable web summit: summaries/web_dev/reliable_web_summit_2021.md
    - kubeconf:
      - utrech 2023: summaries/kubeconf/kubeconf_utrecht_2023.md
    - Lex Fridman:
      - podcast: summaries/lex fridman/lex_friedman_v2.md
    - Stanford:
      - Enterpreneurial thought leader: summaries/stanford/stanford_seminar_enterpreneurial_though_leader.md
      - Technology: summaries/stanford/stanfort_technology.md
    - Strangeloop:
      - year 2023: summaries/strangeloop/strange_loop_2023.md
    - Thoughworks:
      - xconf: summaries/thoughtworks/thoughtworks_xconf_eu_2023.md
    - Usenix:
      - ATC 2023: summaries/usenix/usenix_atc_2023_v2.md
      - Fast 2023: summaries/usenix/usenix_fast_2023.md
      - SRE Americas 2023: summaries/usenix/usenix_sre_americas2023.md
    - Ycombinator:
      - Dalton and Michael: summaries/ycombinator/ycombinator_dalton_michael.md
      - How to build the future: summaries/ycombinator/ycombinator_how_to_build_future.md
      - Startup school: summaries/ycombinator/ycombinator_startup_school.md
  - Blogs:
    - Architecture:
      - Building Distributed Applications with Event-Driven Architecture: blog/architecture/eda.md
    - Design:
      - Design for the Utopia You Want, Not the Dystopia You're In: blog/design/design_for_the_utopia.md
    - Other:
      - Technology Radar Volume 29 - preview: blog/other/tech_rada_trends_preview.md
  - Tags: tags.md
theme:
  name: 'material'
plugins:
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - tags


